#!/usr/bin/env bash
#0. Nginx likes port 80
sudo su
apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx start
service nginx restart
