#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times, 
#but for the 9th iteration, 
#displays Best School and then Hi on a new line.


int=1

while [ $int -le 10 ]
do
    echo "Best School"
    int=$(( int + 1))
if [ $int == 10 ]
    then
      echo "Hi"
    fi
done
