#!/usr/bin/env bash
#1. Run Nginx as Nginx
sudo pkill -o apache2
sudo sed -i "2i\ user nginx; \n" /etc/nginx/nginx.conf
#sudo chmod 744 /etc/nginx/nginx.conf
#sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
