#!/usr/bin/env bash
#2. 7 lines or less
sudo pkill -o apache2
chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 755 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
su nginx -c "service nginx restart"
